name: Render video
on:
    workflow_dispatch:
        inputs:
            postId:
                description: "Put postId here"
                required: true
                default: "uzm67c"
            commentIds:
                description: "Put CommentIds here seperated by a comma"
                required: true
                default: "iab62k6,iab0moh,iab2w5s,iab1ebo,iab8y9f"
jobs:
    render:
        name: Render video
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
            - run: sudo apt update

            - run: sudo apt install ffmpeg
            - run: npm i
            - run: echo $WORKFLOW_INPUT > input-props.json
              env:
                  WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
            - run: npm run build -- --props="./input-props.json"
              env:
                  REMOTION_AZURE_TTS_KEY: ${{secrets.REMOTION_AZURE_TTS_KEY}}
                  REMOTION_AZURE_TTS_REGION: ${{secrets.REMOTION_AZURE_TTS_REGION}}
                  REMOTION_AWS_S3_BUCKET_NAME: ${{secrets.REMOTION_AWS_S3_BUCKET_NAME}}
                  REMOTION_AWS_S3_REGION: ${{secrets.REMOTION_AWS_S3_REGION}}
                  REMOTION_AWS_ACCESS_KEY_ID: ${{secrets.REMOTION_AWS_ACCESS_KEY_ID}}
                  REMOTION_AWS_SECRET_ACCESS_KEY: ${{secrets.REMOTION_AWS_SECRET_ACCESS_KEY}}
                  REMOTION_CLIENT_ID: ${{secrets.REMOTION_CLIENT_ID}}
                  REMOTION_CLIENT_SECRET: ${{secrets.REMOTION_CLIENT_SECRET}}
                  REMOTION_REDDIT_USERNAME: ${{secrets.REMOTION_REDDIT_USERNAME}}
                  REMOTION_REDDIT_PASSWORD: ${{secrets.REMOTION_REDDIT_PASSWORD}}
            - uses: actions/upload-artifact@v2
              with:
                  name: out.mp4
                  path: out/video.mp4
